-- =============================================================================
-- MSFT-SNOWFLAKE QUICKSTART LAB: Dynamic Tables Pipeline
-- =============================================================================
-- Builds a declarative Bronze → Silver → Gold pipeline using Dynamic Tables.
-- Snowflake automatically manages incremental refresh and dependency ordering.
--
-- Pipeline DAG:
--   RAW.ORDERS + RAW.CUSTOMERS + RAW.PRODUCTS
--     → STAGING.DT_ORDERS_CLEANED (Bronze)
--       → CURATED.DT_ORDERS_ENRICHED (Silver)
--         → ANALYTICS.DT_SALES_SUMMARY (Gold)
--         → ANALYTICS.DT_CUSTOMER_360 (Gold)
--
-- Prerequisites: Run phases 01 and 02 (setup + synthetic data).
-- =============================================================================

USE ROLE DEMO_ADMIN;
USE WAREHOUSE DEMO_WH;
USE DATABASE MSFT_SNOWFLAKE_DEMO;

-- =============================================================================
-- BRONZE LAYER — Cleaned raw data
-- =============================================================================

-- Clean and validate raw orders
CREATE OR REPLACE DYNAMIC TABLE STAGING.DT_ORDERS_CLEANED
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = DEMO_WH
  COMMENT = 'Bronze: Cleaned and validated orders'
AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    UPPER(TRIM(ORDER_STATUS)) AS ORDER_STATUS,
    TOTAL_AMOUNT,
    DISCOUNT_AMOUNT,
    SHIPPING_AMOUNT,
    TOTAL_AMOUNT - DISCOUNT_AMOUNT + SHIPPING_AMOUNT AS NET_AMOUNT,
    UPPER(TRIM(PAYMENT_METHOD)) AS PAYMENT_METHOD,
    SHIPPING_ADDRESS,
    UPPER(TRIM(REGION)) AS REGION,
    UPPER(TRIM(CHANNEL)) AS CHANNEL,
    SOURCE_SYSTEM,
    CREATED_AT,
    UPDATED_AT,
    -- Data quality flags
    IFF(TOTAL_AMOUNT > 0, TRUE, FALSE) AS IS_VALID_AMOUNT,
    IFF(CUSTOMER_ID IS NOT NULL AND CUSTOMER_ID > 0, TRUE, FALSE) AS HAS_VALID_CUSTOMER
FROM RAW.ORDERS
WHERE ORDER_DATE IS NOT NULL
  AND TOTAL_AMOUNT IS NOT NULL;

-- Clean clickstream data (from Snowpipe)
CREATE OR REPLACE DYNAMIC TABLE STAGING.DT_CLICKSTREAM_CLEANED
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = DEMO_WH
  COMMENT = 'Bronze: Cleaned website clickstream events'
AS
SELECT
    EVENT_ID,
    SESSION_ID,
    CUSTOMER_ID,
    PAGE_URL,
    UPPER(TRIM(EVENT_TYPE)) AS EVENT_TYPE,
    REFERRER,
    UPPER(TRIM(DEVICE_TYPE)) AS DEVICE_TYPE,
    BROWSER,
    EVENT_TIMESTAMP,
    EVENT_PROPERTIES,
    LOADED_AT
FROM RAW.WEBSITE_CLICKSTREAM
WHERE EVENT_ID IS NOT NULL
  AND EVENT_TIMESTAMP IS NOT NULL;

-- =============================================================================
-- SILVER LAYER — Enriched and joined data
-- =============================================================================

-- Enrich orders with customer and product details
CREATE OR REPLACE DYNAMIC TABLE CURATED.DT_ORDERS_ENRICHED
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = DEMO_WH
  COMMENT = 'Silver: Orders enriched with customer and product info'
AS
SELECT
    o.ORDER_ID,
    o.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME,
    c.EMAIL AS CUSTOMER_EMAIL,
    c.CUSTOMER_SEGMENT,
    c.CITY AS CUSTOMER_CITY,
    c.STATE AS CUSTOMER_STATE,
    o.ORDER_DATE,
    DATE_TRUNC('month', o.ORDER_DATE) AS ORDER_MONTH,
    DATE_TRUNC('quarter', o.ORDER_DATE) AS ORDER_QUARTER,
    YEAR(o.ORDER_DATE) AS ORDER_YEAR,
    o.ORDER_STATUS,
    o.TOTAL_AMOUNT,
    o.DISCOUNT_AMOUNT,
    o.SHIPPING_AMOUNT,
    o.NET_AMOUNT,
    o.PAYMENT_METHOD,
    o.REGION,
    o.CHANNEL,
    o.SOURCE_SYSTEM,
    -- Customer lifetime metrics (at time of order)
    DATEDIFF('day', c.REGISTRATION_DATE, o.ORDER_DATE::DATE) AS CUSTOMER_TENURE_DAYS,
    CASE
        WHEN o.NET_AMOUNT >= 5000 THEN 'High Value'
        WHEN o.NET_AMOUNT >= 1000 THEN 'Medium Value'
        ELSE 'Standard'
    END AS ORDER_VALUE_TIER
FROM STAGING.DT_ORDERS_CLEANED o
LEFT JOIN RAW.CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
WHERE o.IS_VALID_AMOUNT = TRUE
  AND o.HAS_VALID_CUSTOMER = TRUE;

-- Enrich inventory with supplier data
CREATE OR REPLACE DYNAMIC TABLE CURATED.DT_INVENTORY_ENRICHED
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = DEMO_WH
  COMMENT = 'Silver: Inventory enriched with supplier details'
AS
SELECT
    i.INVENTORY_ID,
    i.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY AS PRODUCT_CATEGORY,
    p.BRAND,
    i.WAREHOUSE_LOCATION,
    i.QUANTITY_ON_HAND,
    i.QUANTITY_RESERVED,
    i.QUANTITY_ON_HAND - i.QUANTITY_RESERVED AS QUANTITY_AVAILABLE,
    i.REORDER_POINT,
    IFF(i.QUANTITY_ON_HAND - i.QUANTITY_RESERVED < i.REORDER_POINT, TRUE, FALSE) AS NEEDS_REORDER,
    i.LAST_RESTOCK_DATE,
    s.SUPPLIER_NAME,
    s.COUNTRY AS SUPPLIER_COUNTRY,
    s.LEAD_TIME_DAYS,
    s.RELIABILITY_SCORE
FROM STAGING.ADF_INVENTORY i
LEFT JOIN RAW.PRODUCTS p ON i.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN STAGING.ADF_SUPPLIER_DATA s ON i.SUPPLIER_ID = s.SUPPLIER_ID;

-- =============================================================================
-- GOLD LAYER — Aggregated analytics-ready data
-- =============================================================================

-- Sales summary by region, channel, and time
CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.DT_SALES_SUMMARY
  TARGET_LAG = '15 minutes'
  WAREHOUSE = DEMO_WH
  COMMENT = 'Gold: Sales aggregations by region, channel, and time period'
AS
SELECT
    ORDER_MONTH,
    ORDER_YEAR,
    REGION,
    CHANNEL,
    CUSTOMER_SEGMENT,
    ORDER_VALUE_TIER,
    COUNT(*) AS ORDER_COUNT,
    COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
    SUM(TOTAL_AMOUNT) AS GROSS_REVENUE,
    SUM(DISCOUNT_AMOUNT) AS TOTAL_DISCOUNTS,
    SUM(NET_AMOUNT) AS NET_REVENUE,
    AVG(NET_AMOUNT) AS AVG_ORDER_VALUE,
    MEDIAN(NET_AMOUNT) AS MEDIAN_ORDER_VALUE,
    MAX(NET_AMOUNT) AS MAX_ORDER_VALUE,
    SUM(CASE WHEN ORDER_STATUS = 'CANCELLED' THEN 1 ELSE 0 END) AS CANCELLED_ORDERS,
    ROUND(SUM(CASE WHEN ORDER_STATUS = 'CANCELLED' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2)
        AS CANCELLATION_RATE_PCT
FROM CURATED.DT_ORDERS_ENRICHED
GROUP BY ORDER_MONTH, ORDER_YEAR, REGION, CHANNEL, CUSTOMER_SEGMENT, ORDER_VALUE_TIER;

-- Customer 360 view
CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.DT_CUSTOMER_360
  TARGET_LAG = '15 minutes'
  WAREHOUSE = DEMO_WH
  COMMENT = 'Gold: Customer 360 aggregation for analytics and ML'
AS
SELECT
    o.CUSTOMER_ID,
    o.FIRST_NAME,
    o.LAST_NAME,
    o.CUSTOMER_EMAIL,
    o.CUSTOMER_SEGMENT,
    o.CUSTOMER_CITY,
    o.CUSTOMER_STATE,
    COUNT(*) AS TOTAL_ORDERS,
    SUM(o.NET_AMOUNT) AS LIFETIME_VALUE,
    AVG(o.NET_AMOUNT) AS AVG_ORDER_VALUE,
    MIN(o.ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(o.ORDER_DATE) AS LAST_ORDER_DATE,
    DATEDIFF('day', MAX(o.ORDER_DATE), CURRENT_TIMESTAMP()) AS DAYS_SINCE_LAST_ORDER,
    COUNT(DISTINCT o.REGION) AS REGIONS_ORDERED_FROM,
    COUNT(DISTINCT o.CHANNEL) AS CHANNELS_USED,
    MODE(o.PAYMENT_METHOD) AS PREFERRED_PAYMENT,
    MODE(o.CHANNEL) AS PREFERRED_CHANNEL,
    MODE(o.REGION) AS PRIMARY_REGION,
    SUM(CASE WHEN o.ORDER_STATUS = 'CANCELLED' THEN 1 ELSE 0 END) AS CANCELLED_ORDERS,
    -- RFM-style segmentation
    CASE
        WHEN DATEDIFF('day', MAX(o.ORDER_DATE), CURRENT_TIMESTAMP()) <= 30 THEN 'Active'
        WHEN DATEDIFF('day', MAX(o.ORDER_DATE), CURRENT_TIMESTAMP()) <= 90 THEN 'Warm'
        WHEN DATEDIFF('day', MAX(o.ORDER_DATE), CURRENT_TIMESTAMP()) <= 180 THEN 'Cooling'
        ELSE 'At Risk'
    END AS ENGAGEMENT_STATUS,
    CASE
        WHEN SUM(o.NET_AMOUNT) >= 50000 THEN 'Platinum'
        WHEN SUM(o.NET_AMOUNT) >= 20000 THEN 'Gold'
        WHEN SUM(o.NET_AMOUNT) >= 5000 THEN 'Silver'
        ELSE 'Bronze'
    END AS CUSTOMER_TIER
FROM CURATED.DT_ORDERS_ENRICHED o
GROUP BY o.CUSTOMER_ID, o.FIRST_NAME, o.LAST_NAME, o.CUSTOMER_EMAIL,
         o.CUSTOMER_SEGMENT, o.CUSTOMER_CITY, o.CUSTOMER_STATE;

-- Product performance
CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.DT_PRODUCT_PERFORMANCE
  TARGET_LAG = '15 minutes'
  WAREHOUSE = DEMO_WH
  COMMENT = 'Gold: Product performance metrics'
AS
SELECT
    oi.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.SUB_CATEGORY,
    p.BRAND,
    p.UNIT_PRICE AS LIST_PRICE,
    COUNT(DISTINCT oi.ORDER_ID) AS ORDERS_CONTAINING_PRODUCT,
    SUM(oi.QUANTITY) AS TOTAL_UNITS_SOLD,
    SUM(oi.LINE_TOTAL) AS TOTAL_REVENUE,
    AVG(oi.UNIT_PRICE) AS AVG_SELLING_PRICE,
    AVG(oi.DISCOUNT_PCT) AS AVG_DISCOUNT_PCT,
    -- Review metrics
    r.AVG_RATING,
    r.REVIEW_COUNT,
    r.POSITIVE_REVIEW_PCT
FROM RAW.ORDER_ITEMS oi
LEFT JOIN RAW.PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN (
    SELECT
        PRODUCT_ID,
        ROUND(AVG(RATING), 2) AS AVG_RATING,
        COUNT(*) AS REVIEW_COUNT,
        ROUND(SUM(CASE WHEN RATING >= 4 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS POSITIVE_REVIEW_PCT
    FROM RAW.PRODUCT_REVIEWS
    GROUP BY PRODUCT_ID
) r ON oi.PRODUCT_ID = r.PRODUCT_ID
GROUP BY oi.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY, p.SUB_CATEGORY, p.BRAND,
         p.UNIT_PRICE, r.AVG_RATING, r.REVIEW_COUNT, r.POSITIVE_REVIEW_PCT;

-- =============================================================================
-- VERIFICATION
-- =============================================================================

-- Check dynamic table status
SHOW DYNAMIC TABLES IN DATABASE MSFT_SNOWFLAKE_DEMO;

-- Check refresh history
SELECT NAME, SCHEMA_NAME, STATE, STATE_MESSAGE, TARGET_LAG, REFRESH_MODE
FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY())
WHERE NAME IN ('DT_ORDERS_CLEANED','DT_ORDERS_ENRICHED','DT_SALES_SUMMARY','DT_CUSTOMER_360','DT_PRODUCT_PERFORMANCE')
ORDER BY DATA_TIMESTAMP DESC
LIMIT 20;

-- Sample from gold layer
SELECT * FROM ANALYTICS.DT_SALES_SUMMARY LIMIT 10;
SELECT * FROM ANALYTICS.DT_CUSTOMER_360 ORDER BY LIFETIME_VALUE DESC LIMIT 10;
SELECT * FROM ANALYTICS.DT_PRODUCT_PERFORMANCE ORDER BY TOTAL_REVENUE DESC LIMIT 10;

SELECT 'Dynamic tables pipeline created.' AS STATUS;
